server:
  port: 8080

spring:
  application:
    name: ecommerce-api
  datasource:
    url: jdbc:mysql://localhost:3399/ecommerce?permitMysqlHostAuth=true
    username: root
    password: hh99root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
# Swagger UI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    default-models-expand-depth: 3
    default-model-expand-depth: 3
  show-actuator: false
  model-and-view-allowed: true
